#mybatis配置
mybatis:
  type-aliases-package: com.kw.model
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

# 数据库池配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ssm?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8

#   JPA配置
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

  #  Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
    encoding: UTF-8
  mail:
    host: smtp.qq.com
    username: 841299007@qq.com
    password: beiifclzjbsnbdda
    default-encoding: UTF-8

mail:
  fromMail:
    addr: 841299007@qq.com


  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

logging:
  config: springboot-web/src/main/resources/logback.xml
  level:
    com.kw.mapper: trace



